//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsPresentationFoundation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsPresentationFoundation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string btnAccept {
            get {
                return ResourceManager.GetString("btnAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string btnInfo {
            get {
                return ResourceManager.GetString("btnInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Championship:.
        /// </summary>
        public static string Championship {
            get {
                return ResourceManager.GetString("Championship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain:.
        /// </summary>
        public static string lblCaptain {
            get {
                return ResourceManager.GetString("lblCaptain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIFA:.
        /// </summary>
        public static string lblCode {
            get {
                return ResourceManager.GetString("lblCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string lblCountry {
            get {
                return ResourceManager.GetString("lblCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draws:.
        /// </summary>
        public static string lblDraws {
            get {
                return ResourceManager.GetString("lblDraws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games played:.
        /// </summary>
        public static string lblGamesPlayed {
            get {
                return ResourceManager.GetString("lblGamesPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal differential:.
        /// </summary>
        public static string lblGoalDifferential {
            get {
                return ResourceManager.GetString("lblGoalDifferential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Golas againsts:.
        /// </summary>
        public static string lblGoalsAgainsts {
            get {
                return ResourceManager.GetString("lblGoalsAgainsts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals for:.
        /// </summary>
        public static string lblGoalsFor {
            get {
                return ResourceManager.GetString("lblGoalsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Losses:.
        /// </summary>
        public static string lblLosses {
            get {
                return ResourceManager.GetString("lblLosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position:.
        /// </summary>
        public static string lblPosition {
            get {
                return ResourceManager.GetString("lblPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scored goals:.
        /// </summary>
        public static string lblScoredGoals {
            get {
                return ResourceManager.GetString("lblScoredGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shirt number:.
        /// </summary>
        public static string lblShirtNumber {
            get {
                return ResourceManager.GetString("lblShirtNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wins:.
        /// </summary>
        public static string lblWins {
            get {
                return ResourceManager.GetString("lblWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow cards:.
        /// </summary>
        public static string lblYellowCards {
            get {
                return ResourceManager.GetString("lblYellowCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatian.
        /// </summary>
        public static string rbtnCroatianLanguage {
            get {
                return ResourceManager.GetString("rbtnCroatianLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string rbtnEnglishLanguage {
            get {
                return ResourceManager.GetString("rbtnEnglishLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string rbtnFemale {
            get {
                return ResourceManager.GetString("rbtnFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string rbtnMale {
            get {
                return ResourceManager.GetString("rbtnMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution:.
        /// </summary>
        public static string Resolution {
            get {
                return ResourceManager.GetString("Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowSetting.
        /// </summary>
        public static string WindowSettings {
            get {
                return ResourceManager.GetString("WindowSettings", resourceCulture);
            }
        }
    }
}
